### ISSUE TITLE
Deprecating vue-fire

### ISSUE THREAD

**Issue by posva** [agonbina/vue-fire#2]
Hello,

It looks like some people get confused with this package (https://github.com/vuejs/vuefire/issues/103).
Could you please, deprecate this package in favour of the official one (https://github.com/vuejs/vuefire), which I maintain

This can be achieved running the following command:

```sh
npm deprecate vue-fire 'vue-fire is not maintained anymore, use vuefire instead'
```

(Use the message you want, of course, linking to vuefire is the important part 🙂 )

Thanks!

**Comment by agonbina** [comment]
@posva hey, I just ran the command to deprecate it. Seems like it worked(when running `npm view vue-fire` the json comes back with a "deprecated" attribute) but it doesn't say anything else in the npm page for the package https://www.npmjs.com/package/vue-fire

**Comment by posva** [comment]
Thanks, it worked nicely 🙂 

<img width="642" alt="screen shot 2017-05-25 at 11 19 26" src="https://cloud.githubusercontent.com/assets/664177/26444276/0cdfffb2-413c-11e7-9b93-50c7775f912f.png">

That's enough from my point of view
